import { useState } from 'react'
import JSZip from 'jszip'
import { CheckCircle2, AlertTriangle, Circle, GitBranch, Download } from 'lucide-react'
import { useServersForProject, useBuildsForProject, requestBuild, appendBuildLog } from '../../db/hooks'
import { StudioPage, Field, TextInput } from './StudioField'

function validateProject(project, servers) {
  const issues = []
  if (!project.identity.launcherName) issues.push('Launcher name is not set (Identity tab).')
  if (!project.minecraft.version) issues.push('Minecraft version is not set (Minecraft & server tab).')
  else if (!/^\d+\.\d+(\.\d+)?$/.test(project.minecraft.version)) {
    issues.push('Minecraft version format looks invalid.')
  }
  if (project.minecraft.loader !== 'vanilla' && !project.minecraft.javaRequirement) {
    issues.push('Java requirement is recommended for non-vanilla loaders.')
  }
  if (!servers || servers.length === 0) issues.push('No servers configured — the launcher will have nothing to connect to.')
  if (project.minecraft.ram.max < project.minecraft.ram.min) issues.push('Maximum RAM is lower than minimum RAM.')
  return issues
}

function buildProjectManifest(project, servers) {
  return {
    schema: 'vynix-forge/launcher-project@1',
    generatedAt: new Date().toISOString(),
    identity: project.identity,
    branding: {
      ...project.branding,
      icon: project.branding.icon ? '(embedded — see assets/icon.png)' : null,
      logo: project.branding.logo ? '(embedded — see assets/logo.png)' : null,
      background: project.branding.background ? '(embedded — see assets/background.png)' : null,
      splash: project.branding.splash ? '(embedded — see assets/splash.png)' : null,
    },
    layout: project.layout,
    features: project.features,
    minecraft: project.minecraft,
    servers: (servers || []).map((s) => ({
      name: s.name,
      address: s.address,
      port: s.port,
      loader: s.loader,
      autoConnect: s.autoConnect,
      isDefault: s.isDefault,
    })),
  }
}

async function dataUrlToBlob(dataUrl) {
  const res = await fetch(dataUrl)
  return res.blob()
}

export default function StudioBuild({ project }) {
  const servers = useServersForProject(project.id)
  const builds = useBuildsForProject(project.id)
  const [generating, setGenerating] = useState(false)
  const [repoUrl, setRepoUrl] = useState('')

  const issues = validateProject(project, servers)
  const canGenerate = issues.length === 0

  async function handleGenerate() {
    setGenerating(true)
    const buildId = await requestBuild(project.id)
    try {
      await appendBuildLog(buildId, 'Validating project configuration…', 'validating')
      if (!canGenerate) {
        await appendBuildLog(buildId, `Validation failed: ${issues.join(' ')}`, 'failed')
        setGenerating(false)
        return
      }

      await appendBuildLog(buildId, 'Project validated.')
      await appendBuildLog(buildId, 'Assembling project source…', 'running')

      const zip = new JSZip()
      const manifest = buildProjectManifest(project, servers)
      zip.file('launcher.config.json', JSON.stringify(manifest, null, 2))
      zip.file(
        'README.md',
        `# ${project.identity.launcherName || project.name}\n\n` +
          `Generated by Vynix Forge on ${new Date().toISOString()}.\n\n` +
          `This is a source project, not a compiled application. To produce\n` +
          `installable builds (.exe / .AppImage / .dmg), wire this project into\n` +
          `a build pipeline such as GitHub Actions with electron-builder, or\n` +
          `build it locally.\n\n` +
          `## Configuration\nSee \`launcher.config.json\` for the full launcher\n` +
          `configuration (identity, branding, servers, mods, layout).\n`
      )

      const assets = zip.folder('assets')
      const assetMap = { icon: 'icon', logo: 'logo', background: 'background', splash: 'splash' }
      for (const [key, filename] of Object.entries(assetMap)) {
        const dataUrl = project.branding[key]
        if (dataUrl) {
          const blob = await dataUrlToBlob(dataUrl)
          const ext = blob.type.split('/')[1] || 'png'
          assets.file(`${filename}.${ext}`, blob)
        }
      }

      await appendBuildLog(buildId, 'Source generated.')
      const blob = await zip.generateAsync({ type: 'blob' })
      const url = URL.createObjectURL(blob)
      const a = document.createElement('a')
      a.href = url
      a.download = `${(project.identity.launcherName || project.name).replace(/\s+/g, '-').toLowerCase()}-source.zip`
      a.click()
      URL.revokeObjectURL(url)

      await appendBuildLog(
        buildId,
        'Artifact available: source project (.zip). Compiling to a native installer requires a build environment — see below.',
        'succeeded'
      )
    } catch (e) {
      await appendBuildLog(buildId, `Build failed: ${e.message}`, 'failed')
    } finally {
      setGenerating(false)
    }
  }

  return (
    <StudioPage
      title="Generate & build"
      description="Turn this configuration into a real project you can compile and distribute."
    >
      <div>
        <h3 className="font-display font-medium text-sm mb-2.5">Validation</h3>
        {issues.length === 0 ? (
          <div className="flex items-center gap-2 text-[13px] text-forge-copper-bright border border-forge-border-soft rounded-lg px-3.5 py-2.5">
            <CheckCircle2 size={15} />
            Configuration looks valid.
          </div>
        ) : (
          <ul className="space-y-1.5">
            {issues.map((issue, i) => (
              <li key={i} className="flex items-start gap-2 text-[13px] text-forge-warn border border-forge-border-soft rounded-lg px-3.5 py-2.5">
                <AlertTriangle size={14} className="mt-0.5 shrink-0" />
                {issue}
              </li>
            ))}
          </ul>
        )}
      </div>

      <div>
        <h3 className="font-display font-medium text-sm mb-2.5">Pipeline</h3>
        <div className="space-y-1">
          <PipelineStep label="Source generated" status={canGenerate ? 'available' : 'blocked'} />
          <PipelineStep label="Project validated" status={canGenerate ? 'available' : 'blocked'} />
          <PipelineStep label="Build requested" status="requires-github" />
          <PipelineStep label="Build running" status="requires-github" />
          <PipelineStep label="Build succeeded" status="requires-github" />
          <PipelineStep label="Artifact available" status="requires-github" />
        </div>
        <p className="mt-2 text-[11.5px] text-forge-text-faint">
          Vynix Forge generates real source and configuration in your browser for free.
          Compiling that source into a signed, installable app for Windows, Linux, or
          macOS needs an actual build machine — connect a GitHub repository below to
          run that step with GitHub Actions.
        </p>
      </div>

      <button
        onClick={handleGenerate}
        disabled={generating}
        className="flex items-center gap-2 rounded-md bg-forge-ember px-4 py-2.5 text-sm font-medium text-forge-bg disabled:opacity-50 w-fit"
      >
        <Download size={15} />
        {generating ? 'Generating…' : 'Generate & download source project'}
      </button>

      <div className="border border-forge-border-soft rounded-lg p-4 space-y-3">
        <div className="flex items-center gap-2">
          <GitBranch size={15} />
          <h3 className="font-display font-medium text-sm">Connect GitHub for real builds</h3>
        </div>
        <p className="text-[12.5px] text-forge-text-dim">
          Not connected. Pointing this project at a repository lets you push the
          generated source and run a GitHub Actions workflow that produces real
          Windows, Linux, and macOS artifacts.
        </p>
        <Field label="Repository URL">
          <TextInput
            value={repoUrl}
            onChange={(e) => setRepoUrl(e.target.value)}
            placeholder="https://github.com/you/your-launcher"
          />
        </Field>
        <button
          disabled
          className="text-[12.5px] rounded-md border border-forge-border px-3 py-2 text-forge-text-faint cursor-not-allowed w-fit"
          title="GitHub integration isn't wired up in this build of Vynix Forge yet."
        >
          Connect repository
        </button>
      </div>

      <div>
        <h3 className="font-display font-medium text-sm mb-2.5">Build history</h3>
        {(!builds || builds.length === 0) ? (
          <p className="text-[13px] text-forge-text-faint py-6 text-center border border-dashed border-forge-border-soft rounded-lg">
            No builds yet.
          </p>
        ) : (
          <ul className="border border-forge-border-soft rounded-lg divide-y divide-forge-border-soft">
            {builds.map((b) => (
              <li key={b.id} className="px-3.5 py-2.5">
                <div className="flex items-center justify-between">
                  <span className="text-[13px]">{b.id}</span>
                  <span className={`text-[11.5px] capitalize ${
                    b.status === 'succeeded' ? 'text-forge-copper-bright' :
                    b.status === 'failed' ? 'text-forge-danger' : 'text-forge-text-faint'
                  }`}>{b.status}</span>
                </div>
                <p className="text-[11px] text-forge-text-faint mt-1">{b.log[b.log.length - 1]}</p>
              </li>
            ))}
          </ul>
        )}
      </div>
    </StudioPage>
  )
}

function PipelineStep({ label, status }) {
  const icon =
    status === 'available' ? (
      <CheckCircle2 size={14} className="text-forge-copper-bright" />
    ) : status === 'requires-github' ? (
      <Circle size={14} className="text-forge-text-faint" />
    ) : (
      <Circle size={14} className="text-forge-warn" />
    )
  return (
    <div className="flex items-center gap-2.5 text-[13px] px-1 py-1.5">
      {icon}
      <span className={status === 'requires-github' ? 'text-forge-text-faint' : ''}>{label}</span>
      {status === 'requires-github' && (
        <span className="text-[10.5px] text-forge-text-faint ml-auto">requires GitHub</span>
      )}
    </div>
  )
}
